version: "3.8"

services:
  frontend:
    image: ${AWS_ECR_URL}/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:5173"
    environment:
      API_BASE_URL: https://www.dev-ops-project.com/api


  backend:
    image: ${AWS_ECR_URL}/backend:latest
    container_name: backend
    ports:
      - "8800:8800"
    environment:
      DATABASE_HOST: ${RDS_HOST}
      DATABASE_USER: ${RDS_USER}
      DATABASE_PASSWORD: ${RDS_PASSWORD}
      DATABASE_NAME: ${RDS_NAME}
      DATABASE_PORT: ${RDS_PORT}
