services:
  frontend:
    image: ${AWS_ECR_URL}/frontend:${TEST_TAG}
    container_name: bookapp-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: ${AWS_ECR_URL}/backend:${TEST_TAG}
    container_name: bookapp-backend
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

    volumes:
      - my-db:/var/lib/mysql
      - ../source-repo/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 50s
      retries: 5

volumes:
  my-db:
