version: "3.8"

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/dev-ops-project.com/fullchain.pem:/etc/ssl/certs/devops-fullchain.pem:ro
      - /etc/letsencrypt/live/dev-ops-project.com/privkey.pem:/etc/ssl/private/devops-privkey.pem:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: ${AWS_ECR_URL}/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    expose:
      - "5173"
    environment:
      VITE_BOOK_APP_API_BASE_URL: https://www.dev-ops-project.com/api


  backend:
    image: ${AWS_ECR_URL}/backend:latest
    container_name: backend
    expose:
      - "8800"
    environment:
      DATABASE_HOST: ${RDS_HOST}
      DATABASE_USER: ${RDS_USER}
      DATABASE_PASSWORD: ${RDS_PASSWORD}
      DATABASE_NAME: ${RDS_NAME}
      DATABASE_PORT: ${RDS_PORT}
