services:
  frontend:
    image: ${AWS_ECR_URL}/frontend:${TEST_TAG}
    container_name: bookapp-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    image: ${AWS_ECR_URL}/backend:${TEST_TAG}
    container_name: bookapp-backend
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: devops
      DATABASE_PASSWORD: test1234
      DATABASE_NAME: test
      DATABASE_PORT: 3306

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: devops
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - my-db:/var/lib/mysql
      - ../source-repo/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 50s
      retries: 5

volumes:
  my-db:
